### ISSUE TITLE
Build fail for AWS SDK 1.9.19

### ISSUE THREAD

**Issue by MaxKhlupnov** [amzn/amazon-s3-gst-plugin#18] opened 2021-05-16 07:38 UTC
mesos build completed successfully, but ninja fail with linking error.

```
makhlu@i104299575:~/amazon-s3-gst-plugin/build$ ninja
[0/1] Regenerating build files.
The Meson build system
Version: 0.58.0
Source dir: /home/makhlu/amazon-s3-gst-plugin
Build dir: /home/makhlu/amazon-s3-gst-plugin/build
Build type: native build
Project name: amazon-s3-gst-plugin
Project version: 0.1.0
C compiler for the host machine: cc (gcc 9.3.0 "cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0")
C linker for the host machine: cc ld.bfd 2.34
C++ compiler for the host machine: c++ (gcc 9.3.0 "c++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0")
C++ linker for the host machine: c++ ld.bfd 2.34
Host machine cpu family: x86_64
Host machine cpu: x86_64
Dependency glib-2.0 found: YES 2.64.6 (cached)
Dependency gstreamer-1.0 found: YES 1.16.2 (cached)
Dependency gstreamer-base-1.0 found: YES 1.16.2 (cached)
Dependency gstreamer-check-1.0 found: YES 1.16.2 (cached)
Dependency aws-cpp-sdk-s3 found: YES 1.9.19 (cached)
Dependency aws-cpp-sdk-sts found: YES 1.9.19 (cached)
Library aws-c-common found: YES
Library aws-crt-cpp found: YES
Configuring config.h using configuration
Configuring gstreamer-aws-1.0.pc using configuration
Build targets in project: 4

Found ninja-1.10.0 at /usr/bin/ninja
[1/3] Linking target src/libgsts3elements.so
FAILED: src/libgsts3elements.so
c++  -o src/libgsts3elements.so src/libgsts3elements.so.p/gsts3elements.c.o src/libgsts3elements.so.p/gsts3sink.c.o src/libgsts3elements.so.p/gsts3uploader.c.o -Wl,--as-needed -Wl,--no-undefined -shared -fPIC -Wl,--start-group -Wl,-soname,libgsts3elements.so '-Wl,-rpath,$ORIGIN/' -Wl,-rpath-link,/home/makhlu/amazon-s3-gst-plugin/build/src src/libmultipartuploader.a src/libgstawscredentials-1.0.so /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so /usr/lib/x86_64-linux-gnu/libgobject-2.0.so /usr/lib/x86_64-linux-gnu/libglib-2.0.so /usr/lib/x86_64-linux-gnu/libgstbase-1.0.so /usr/local/lib/libaws-cpp-sdk-s3.so /usr/local/lib/libaws-cpp-sdk-core.so -Wl,--end-group
/usr/bin/ld: src/libmultipartuploader.a(gsts3multipartuploader.cpp.o): in function `Aws::Crt::StlAllocator<unsigned char*>::StlAllocator()':
/usr/local/include/aws/crt/StlAllocator.h:24: undefined reference to `Aws::Crt::g_allocator'
/usr/bin/ld: src/libmultipartuploader.a(gsts3multipartuploader.cpp.o): in function `Aws::Crt::StlAllocator<unsigned char*>::deallocate(unsigned char**, unsigned long)':
/usr/local/include/aws/crt/StlAllocator.h:56: undefined reference to `aws_mem_release'
/usr/bin/ld: src/libmultipartuploader.a(gsts3multipartuploader.cpp.o): in function `Aws::Crt::StlAllocator<char>::deallocate(char*, unsigned long)':
/usr/local/include/aws/crt/StlAllocator.h:56: undefined reference to `aws_mem_release'
/usr/bin/ld: /usr/local/include/aws/crt/StlAllocator.h:56: undefined reference to `aws_mem_release'
/usr/bin/ld: /usr/local/include/aws/crt/StlAllocator.h:56: undefined reference to `aws_mem_release'
/usr/bin/ld: /usr/local/include/aws/crt/StlAllocator.h:56: undefined reference to `aws_mem_release'
/usr/bin/ld: src/libmultipartuploader.a(gsts3multipartuploader.cpp.o):/usr/local/include/aws/crt/StlAllocator.h:56: more undefined references to `aws_mem_release' follow
/usr/bin/ld: src/libmultipartuploader.a(gsts3multipartuploader.cpp.o): in function `Aws::Crt::StlAllocator<unsigned char*>::StlAllocator()':
/usr/local/include/aws/crt/StlAllocator.h:24: undefined reference to `Aws::Crt::g_allocator'
/usr/bin/ld: src/libmultipartuploader.a(gsts3multipartuploader.cpp.o): in function `Aws::Crt::StlAllocator<char>::StlAllocator()':
/usr/local/include/aws/crt/StlAllocator.h:24: undefined reference to `Aws::Crt::g_allocator'
/usr/bin/ld: src/libmultipartuploader.a(gsts3multipartuploader.cpp.o): in function `Aws::Crt::StlAllocator<char>::deallocate(char*, unsigned long)':
/usr/local/include/aws/crt/StlAllocator.h:56: undefined reference to `aws_mem_release'
/usr/bin/ld: /usr/local/include/aws/crt/StlAllocator.h:56: undefined reference to `aws_mem_release'
/usr/bin/ld: /usr/local/include/aws/crt/StlAllocator.h:56: undefined reference to `aws_mem_release'
/usr/bin/ld: /usr/local/include/aws/crt/StlAllocator.h:56: undefined reference to `aws_mem_release'
/usr/bin/ld: /usr/local/include/aws/crt/StlAllocator.h:56: undefined reference to `aws_mem_release'
/usr/bin/ld: src/libmultipartuploader.a(gsts3multipartuploader.cpp.o):/usr/local/include/aws/crt/StlAllocator.h:56: more undefined references to `aws_mem_release' follow
/usr/bin/ld: src/libmultipartuploader.a(gsts3multipartuploader.cpp.o): in function `Aws::Crt::StlAllocator<char>::StlAllocator()':
/usr/local/include/aws/crt/StlAllocator.h:24: undefined reference to `Aws::Crt::g_allocator'
/usr/bin/ld: src/libmultipartuploader.a(gsts3multipartuploader.cpp.o): in function `Aws::Crt::StlAllocator<char>::deallocate(char*, unsigned long)':
/usr/local/include/aws/crt/StlAllocator.h:56: undefined reference to `aws_mem_release'
/usr/bin/ld: /usr/local/include/aws/crt/StlAllocator.h:56: undefined reference to `aws_mem_release'
/usr/bin/ld: /usr/local/include/aws/crt/StlAllocator.h:56: undefined reference to `aws_mem_release'
/usr/bin/ld: /usr/local/include/aws/crt/StlAllocator.h:56: undefined reference to `aws_mem_release'
/usr/bin/ld: /usr/local/include/aws/crt/StlAllocator.h:56: undefined reference to `aws_mem_release'
/usr/bin/ld: src/libmultipartuploader.a(gsts3multipartuploader.cpp.o):/usr/local/include/aws/crt/StlAllocator.h:56: more undefined references to `aws_mem_release' follow
/usr/bin/ld: src/libmultipartuploader.a(gsts3multipartuploader.cpp.o): in function `Aws::Crt::StlAllocator<char>::StlAllocator()':
/usr/local/include/aws/crt/StlAllocator.h:24: undefined reference to `Aws::Crt::g_allocator'
/usr/bin/ld: src/libmultipartuploader.a(gsts3multipartuploader.cpp.o): in function `Aws::Crt::StlAllocator<char>::deallocate(char*, unsigned long)':
/usr/local/include/aws/crt/StlAllocator.h:56: undefined reference to `aws_mem_release'
/usr/bin/ld: /usr/local/include/aws/crt/StlAllocator.h:56: undefined reference to `aws_mem_release'
/usr/bin/ld: src/libmultipartuploader.a(gsts3multipartuploader.cpp.o): in function `Aws::Crt::StlAllocator<Aws::S3::Model::CompletedPart>::allocate(unsigned long, void const*)':
/usr/local/include/aws/crt/StlAllocator.h:50: undefined reference to `aws_mem_acquire'
/usr/bin/ld: src/libmultipartuploader.a(gsts3multipartuploader.cpp.o): in function `Aws::Crt::StlAllocator<Aws::S3::Model::CompletedPart>::deallocate(Aws::S3::Model::CompletedPart*, unsigned long)':
/usr/local/include/aws/crt/StlAllocator.h:56: undefined reference to `aws_mem_release'
/usr/bin/ld: src/libmultipartuploader.a(gsts3multipartuploader.cpp.o): in function `Aws::Crt::StlAllocator<char>::deallocate(char*, unsigned long)':
/usr/local/include/aws/crt/StlAllocator.h:56: undefined reference to `aws_mem_release'
/usr/bin/ld: /usr/local/include/aws/crt/StlAllocator.h:56: undefined reference to `aws_mem_release'
/usr/bin/ld: /usr/local/include/aws/crt/StlAllocator.h:56: undefined reference to `aws_mem_release'
/usr/bin/ld: src/libmultipartuploader.a(gsts3multipartuploader.cpp.o): in function `Aws::Crt::StlAllocator<Aws::S3::Model::CompletedPart>::deallocate(Aws::S3::Model::CompletedPart*, unsigned long)':
/usr/local/include/aws/crt/StlAllocator.h:56: undefined reference to `aws_mem_release'
/usr/bin/ld: src/libmultipartuploader.a(gsts3multipartuploader.cpp.o):/usr/local/include/aws/crt/StlAllocator.h:56: more undefined references to `aws_mem_release' follow
/usr/bin/ld: src/libmultipartuploader.a(gsts3multipartuploader.cpp.o): in function `Aws::Crt::StlAllocator<char>::StlAllocator()':
/usr/local/include/aws/crt/StlAllocator.h:24: undefined reference to `Aws::Crt::g_allocator'
/usr/bin/ld: src/libmultipartuploader.a(gsts3multipartuploader.cpp.o): in function `Aws::Crt::StlAllocator<char>::deallocate(char*, unsigned long)':
/usr/local/include/aws/crt/StlAllocator.h:56: undefined reference to `aws_mem_release'
/usr/bin/ld: src/libmultipartuploader.a(gsts3multipartuploader.cpp.o): in function `Aws::Crt::StlAllocator<char>::StlAllocator()':
/usr/local/include/aws/crt/StlAllocator.h:24: undefined reference to `Aws::Crt::g_allocator'
/usr/bin/ld: src/libmultipartuploader.a(gsts3multipartuploader.cpp.o): in function `Aws::Crt::StlAllocator<char>::deallocate(char*, unsigned long)':
/usr/local/include/aws/crt/StlAllocator.h:56: undefined reference to `aws_mem_release'
/usr/bin/ld: /usr/local/include/aws/crt/StlAllocator.h:56: undefined reference to `aws_mem_release'
/usr/bin/ld: /usr/local/include/aws/crt/StlAllocator.h:56: undefined reference to `aws_mem_release'
/usr/bin/ld: /usr/local/include/aws/crt/StlAllocator.h:56: undefined reference to `aws_mem_release'
/usr/bin/ld: /usr/local/include/aws/crt/StlAllocator.h:56: undefined reference to `aws_mem_release'
/usr/bin/ld: src/libmultipartuploader.a(gsts3multipartuploader.cpp.o):/usr/local/include/aws/crt/StlAllocator.h:56: more undefined references to `aws_mem_release' follow
/usr/bin/ld: src/libmultipartuploader.a(gsts3multipartuploader.cpp.o): in function `Aws::Crt::StlAllocator<char>::StlAllocator()':
/usr/local/include/aws/crt/StlAllocator.h:24: undefined reference to `Aws::Crt::g_allocator'
/usr/bin/ld: src/libmultipartuploader.a(gsts3multipartuploader.cpp.o): in function `Aws::Crt::StlAllocator<char>::deallocate(char*, unsigned long)':
/usr/local/include/aws/crt/StlAllocator.h:56: undefined reference to `aws_mem_release'
/usr/bin/ld: /usr/local/include/aws/crt/StlAllocator.h:56: undefined reference to `aws_mem_release'
/usr/bin/ld: /usr/local/include/aws/crt/StlAllocator.h:56: undefined reference to `aws_mem_release'
/usr/bin/ld: /usr/local/include/aws/crt/StlAllocator.h:56: undefined reference to `aws_mem_release'
/usr/bin/ld: /usr/local/include/aws/crt/StlAllocator.h:56: undefined reference to `aws_mem_release'
/usr/bin/ld: src/libmultipartuploader.a(gsts3multipartuploader.cpp.o):/usr/local/include/aws/crt/StlAllocator.h:56: more undefined references to `aws_mem_release' follow
/usr/bin/ld: src/libmultipartuploader.a(gsts3multipartuploader.cpp.o): in function `Aws::Crt::StlAllocator<unsigned char*>::allocate(unsigned long, void const*)':
/usr/local/include/aws/crt/StlAllocator.h:50: undefined reference to `aws_mem_acquire'
/usr/bin/ld: src/libmultipartuploader.a(gsts3multipartuploader.cpp.o): in function `Aws::Crt::StlAllocator<unsigned char*>::deallocate(unsigned char**, unsigned long)':
/usr/local/include/aws/crt/StlAllocator.h:56: undefined reference to `aws_mem_release'
/usr/bin/ld: src/libmultipartuploader.a(gsts3multipartuploader.cpp.o): in function `Aws::Crt::StlAllocator<unsigned char*>::allocate(unsigned long, void const*)':
/usr/local/include/aws/crt/StlAllocator.h:50: undefined reference to `aws_mem_acquire'
/usr/bin/ld: src/libmultipartuploader.a(gsts3multipartuploader.cpp.o): in function `Aws::Crt::StlAllocator<unsigned char*>::deallocate(unsigned char**, unsigned long)':
/usr/local/include/aws/crt/StlAllocator.h:56: undefined reference to `aws_mem_release'
/usr/bin/ld: src/libmultipartuploader.a(gsts3multipartuploader.cpp.o): in function `Aws::Crt::StlAllocator<char>::allocate(unsigned long, void const*)':
/usr/local/include/aws/crt/StlAllocator.h:50: undefined reference to `aws_mem_acquire'
/usr/bin/ld: /usr/local/include/aws/crt/StlAllocator.h:50: undefined reference to `aws_mem_acquire'
/usr/bin/ld: /usr/local/include/aws/crt/StlAllocator.h:50: undefined reference to `aws_mem_acquire'
/usr/bin/ld: src/libmultipartuploader.a(gsts3multipartuploader.cpp.o): in function `Aws::Crt::StlAllocator<char>::deallocate(char*, unsigned long)':
/usr/local/include/aws/crt/StlAllocator.h:56: undefined reference to `aws_mem_release'
/usr/bin/ld: /usr/local/include/aws/crt/StlAllocator.h:56: undefined reference to `aws_mem_release'
/usr/bin/ld: /usr/local/include/aws/crt/StlAllocator.h:56: undefined reference to `aws_mem_release'
/usr/bin/ld: /usr/local/include/aws/crt/StlAllocator.h:56: undefined reference to `aws_mem_release'
/usr/bin/ld: src/libmultipartuploader.a(gsts3multipartuploader.cpp.o): in function `Aws::Crt::StlAllocator<Aws::S3::Model::CompletedPart>::allocate(unsigned long, void const*)':
/usr/local/include/aws/crt/StlAllocator.h:50: undefined reference to `aws_mem_acquire'
/usr/bin/ld: src/libmultipartuploader.a(gsts3multipartuploader.cpp.o): in function `Aws::Crt::StlAllocator<char>::deallocate(char*, unsigned long)':
/usr/local/include/aws/crt/StlAllocator.h:56: undefined reference to `aws_mem_release'
/usr/bin/ld: src/libmultipartuploader.a(gsts3multipartuploader.cpp.o): in function `Aws::Crt::StlAllocator<Aws::S3::Model::CompletedPart>::deallocate(Aws::S3::Model::CompletedPart*, unsigned long)':
/usr/local/include/aws/crt/StlAllocator.h:56: undefined reference to `aws_mem_release'
/usr/bin/ld: src/libmultipartuploader.a(gsts3multipartuploader.cpp.o): in function `Aws::Crt::StlAllocator<char>::deallocate(char*, unsigned long)':
/usr/local/include/aws/crt/StlAllocator.h:56: undefined reference to `aws_mem_release'
/usr/bin/ld: /usr/local/include/aws/crt/StlAllocator.h:56: undefined reference to `aws_mem_release'
/usr/bin/ld: /usr/local/include/aws/crt/StlAllocator.h:56: undefined reference to `aws_mem_release'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

**Comment by louisharris** [comment] 2021-06-07 10:52
Looks specific to the linking of the new `aws_crt_cpp` dependency added, will require some further investigation.

**Comment by smthsm** [comment] 2023-03-06 14:48
Hi @MaxKhlupnov, apologies for not getting back to you sooner on this. And thanks for raising the PR. I've managed to reproduce the issue with SDK v1.9 but I'm unsure if the fix is still needed.

The AWS SDK changed how the CRT lib dependencies are handled in v1.10 (they're now included as submodules, see the [SDK README](https://github.com/aws/aws-sdk-cpp/blob/51943bee5e5f1acc79de3f2c3ced82b3bbc13aee/README.md#version-110-is-now-available) for more info), so that users of the SDK no longer need to include it as an explicit dependency.

Since commit [b8ecca6](https://github.com/amzn/amazon-s3-gst-plugin/commit/b8ecca63791e6a4f9559b47d32132144d2d191ab), this project requires at least v1.10.30 of the SDK, so you'll need to update your SDK build to at least that version and to pull in the submodules as described in the SDK README (assuming you're building from source).

Please let me know if that's still not working for you and we can look to get the PR updated and merged.

**Comment by smthsm** [comment] 2023-04-24 10:37
I'm going to close this issue out for now. Please feel free to re-open it or raise a new one if you are still having issues with the build.

**Closed as not planned by smthsm** 2023-04-24 10:37 UTC
