### ISSUE TITLE
Build failed on Mac OS Catalina (ninja: build stopped: subcommand failed)

### ISSUE THREAD

**Issue by pecha7x** [amzn/amazon-s3-gst-plugin#33] opened 2023-05-25 12:12 UTC
Hello guys,

`meson build` results - 

```
pecha7x@MBP-Artem-2 amazon-s3-gst-plugin % meson build 
The Meson build system
Version: 1.1.0
Source dir: /Users/pecha7x/react_projects/bilingual/amazon-s3-gst-plugin
Build dir: /Users/pecha7x/react_projects/bilingual/amazon-s3-gst-plugin/build
Build type: native build
Project name: amazon-s3-gst-plugin
Project version: 0.2.0
C compiler for the host machine: cc (clang 12.0.0 "Apple clang version 12.0.0 (clang-1200.0.32.29)")
C linker for the host machine: cc ld64 609.8
C++ compiler for the host machine: c++ (clang 12.0.0 "Apple clang version 12.0.0 (clang-1200.0.32.29)")
C++ linker for the host machine: c++ ld64 609.8
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /Library/Frameworks/GStreamer.framework/Versions/1.0/bin/pkg-config (0.29.2)
Run-time dependency glib-2.0 found: YES 2.74.4
Run-time dependency gstreamer-1.0 found: YES 1.22.2
Run-time dependency gstreamer-base-1.0 found: YES 1.22.2
Run-time dependency gstreamer-check-1.0 found: YES 1.22.2
Found CMake: /usr/local/bin/cmake (3.21.1)
WARNING: CMake: Dependency aws-cpp-sdk-core for aws-cpp-sdk-s3 was not found
Run-time dependency aws-cpp-sdk-s3 found: YES 1.10.30
WARNING: CMake: Dependency aws-cpp-sdk-core for aws-cpp-sdk-sts was not found
Run-time dependency aws-cpp-sdk-sts found: YES 1.10.30
Configuring config.h using configuration
Configuring gstreamer-aws-1.0.pc using configuration
Build targets in project: 4

Found ninja-1.11.1 at /usr/local/bin/ninja
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
```

and then `cd build && ninja` ([full_error_log.log](https://github.com/amzn/amazon-s3-gst-plugin/files/11564616/full_error_log.log)) - 

```
pecha7x@MBP-Artem-2 amazon-s3-gst-plugin % cd build && ninja
[5/12] Compiling C++ object src/libgst...ls-1.0.dylib.p/gstawscredentials.cpp.o
FAILED: src/libgstawscredentials-1.0.dylib.p/gstawscredentials.cpp.o 
c++ -Isrc/libgstawscredentials-1.0.dylib.p -Isrc -I../src -I/usr/local/include -I/Library/Frameworks/GStreamer.framework/Versions/1.0/lib/pkgconfig/../../include/gstreamer-1.0 -I/Library/Frameworks/GStreamer.framework/Versions/1.0/lib/pkgconfig/../../include -I/Library/Frameworks/GStreamer.framework/Versions/1.0/lib/pkgconfig/../../include/glib-2.0 -I/Library/Frameworks/GStreamer.framework/Versions/1.0/lib/pkgconfig/../../lib/glib-2.0/include -fcolor-diagnostics -Wall -Winvalid-pch -Wextra -O2 -g -DGST_EXPORTS -MD -MQ src/libgstawscredentials-1.0.dylib.p/gstawscredentials.cpp.o -MF src/libgstawscredentials-1.0.dylib.p/gstawscredentials.cpp.o.d -o src/libgstawscredentials-1.0.dylib.p/gstawscredentials.cpp.o -c ../src/gstawscredentials.cpp
In file included from ../src/gstawscredentials.cpp:19:
In file included from ../src/gstawscredentials.hpp:24:
In file included from /usr/local/include/aws/core/auth/AWSCredentialsProvider.h:11:
In file included from /usr/local/include/aws/core/utils/DateTime.h:9:
In file included from /usr/local/include/aws/core/utils/memory/stl/AWSString.h:10:
In file included from /usr/local/include/aws/core/utils/memory/stl/AWSAllocator.h:11:
In file included from /usr/local/include/aws/core/utils/memory/AWSMemory.h:10:
/usr/local/include/aws/core/utils/memory/MemorySystemInterface.h:25:52: warning: defaulted function definitions are a C++11 extension [-Wc++11-extensions]
                virtual ~MemorySystemInterface() = default;
                                                   ^
In file included from ../src/gstawscredentials.cpp:19:
In file included from ../src/gstawscredentials.hpp:24:
In file included from /usr/local/include/aws/core/auth/AWSCredentialsProvider.h:11:
In file included from /usr/local/include/aws/core/utils/DateTime.h:9:
In file included from /usr/local/include/aws/core/utils/memory/stl/AWSString.h:10:
In file included from /usr/local/include/aws/core/utils/memory/stl/AWSAllocator.h:11:
/usr/local/include/aws/core/utils/memory/AWSMemory.h:62:35: warning: variadic templates are a C++11 extension [-Wc++11-extensions]
    template<typename T, typename ...ArgTypes>
                                  ^
/usr/local/include/aws/core/utils/memory/AWSMemory.h:63:47: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
    T* New(const char* allocationTag, ArgTypes&&... args)
                                              ^
/usr/local/include/aws/core/utils/memory/AWSMemory.h:153:78: error: 'T' does not refer to a value
            std::size_t headerSize = (std::max)(sizeof(std::size_t), alignof(T));
            
            ......
            
fatal error: too many errors emitted, stopping now [-ferror-limit=]
65 warnings and 20 errors generated.
ninja: build stopped: subcommand failed.    
```

**Comment by pecha7x** [comment] 2023-05-25 12:35
some additional info - 
`aws-sdk` was installed by next steps -

1. git clone --recurse-submodules --depth 1 https://github.com/aws/aws-sdk-cpp.git -b 1.10.30
2. mkdir aws_sdk_build
3. cd aws_sdk_build
4. cmake ../aws-sdk-cpp -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PREFIX_PATH=/usr/local/ -DCMAKE_INSTALL_PREFIX=/usr/local/ -DBUILD_ONLY="s3;sts"
5. make
6. make install

Before I was tried to use a last version of the SDK, but I've got the same error when tried to build the plugin.

**Comment by russnic** [comment] 2023-06-07 14:50
Hi Artem,

Sorry for the delayed reply. 

We have reproduced the issue internally and are currently troubleshooting.

We'll get back to you once we know more.

Thank you!

Nic

**Comment by smthsm** [comment] 2023-06-30 10:28
Hi @pecha7x,

It looks like the errors occurred because meson couldn't find the pkgconfig files for the SDK, so it didn't set the cflags required to compile anything that includes the SDK headers (in particular `-std=c++11` was missing). You can check for this error in `meson-logs/meson-log.txt` to confirm:
```
Package aws-cpp-sdk-sts was not found in the pkg-config search path.
Perhaps you should add the directory containing `aws-cpp-sdk-sts.pc'
to the PKG_CONFIG_PATH environment variable
```

Doing as the message suggests (i.e. `PKG_CONFIG_PATH=/usr/local/lib/pkgconfig meson build`) solves that issue, but unfortunately the build still fails because of some unexpected differences in how the compiler toolchain behaves on macos. 

I'll get a PR up shortly with a fix for that.

**Comment by smthsm** [comment] 2023-07-12 14:04
@pecha7x - could you try building against the latest changes please?

**Comment by johnbabat** [comment] 2023-07-19 13:38
We are closing this ticket as this is working as expected. Feel free to raise issue if this still does not work for you

**Closed as completed by johnbabat** 2023-07-19 13:38 UTC
